sonar.projectKey=SirDarquan_delisha-marie
sonar.organization=sirdarquan


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=delisha-marie
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./projects/delisha-marie
sonar.exclusions=projects/delisha-marie/e2e/**,projects/delisha-marie/src/app/**/**.spec.ts
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=./coverage/delisha-marie/lcov.info