sonar.projectKey=SirDarquan_delisha-marie
sonar.organization=sirdarquan

# Set sources to root so that paths in lcov.info (which start with 'projects/...') match
sonar.sources=.
sonar.inclusions=projects/delisha-marie/**/*,projects/admin-delisha-marie/**/*
sonar.tests=.
sonar.test.inclusions=projects/delisha-marie/**/*.spec.ts,projects/admin-delisha-marie/**/*.spec.ts
sonar.exclusions=node_modules/**, **/e2e/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Coverage reporting 
sonar.javascript.lcov.reportPaths=coverage/delisha-marie/lcov.info,coverage/admin-delisha-marie/lcov.info
