sonar.projectKey=SirDarquan_delisha-marie
sonar.organization=sirdarquan

# Define sources and tests relative to the root
# Using root (.) and inclusions/exclusions is more robust for path mapping in coverage reports
sonar.sources=./projects/delisha-marie
# sonar.tests=./projects/delisha-marie
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**, **/dist/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Coverage reporting 
sonar.javascript.lcov.reportPaths=coverage/delisha-marie/lcov.info
