name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'

    - run: npm ci
    - run: npm run build

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Configure Docker for Artifact Registry'
      run: |
        gcloud auth configure-docker northamerica-south1-docker.pkg.dev

    - name: 'Build and Push Docker Image'
      run: |
        docker build -t northamerica-south1-docker.pkg.dev/delisha-marie/delisha-marie/delisha-marie-app:${{ github.sha }} .
        docker push northamerica-south1-docker.pkg.dev/delisha-marie/delisha-marie/delisha-marie-app:${{ github.sha }}

    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'delisha-marie'
        image: 'northamerica-south1-docker.pkg.dev/delisha-marie/delisha-marie/delisha-marie-app:${{ github.sha }}'
        region: 'northamerica-south1'
