name: "Update Angular Action"
on: # when the action should run. Can also be a CRON or in response to external events. see https://git.io/JeBz1
  schedule:
    - cron: '30 10 * * 2,4' # Tuesdays and Thursdays at 10:30 UTC (5:30 AM EST)
  workflow_dispatch: # Enable manual triggers

permissions:
  pull-requests: write
  contents: write

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies # the magic happens here!
        uses: fast-facts/ng-update@v1
        with:
          base-branch: main
          repo-token: ${{ secrets.GITHUB_TOKEN }}
